-- Staging de borradores del lote orgánico.
-- Grok Bot lee filas pendiente y escribe el borrador. Nadie envía desde aquí.
-- Correr en el SQL Editor: el host directo de Postgres es solo IPv6
-- y desde esta Mac no enruta.

CREATE TABLE IF NOT EXISTS organic_borradores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id bigint NOT NULL,
    empresa text NOT NULL,
    dominio text NOT NULL,
    pais text NOT NULL DEFAULT 'sin dato',
    contacto jsonb NOT NULL DEFAULT '{}'::jsonb,
    idioma text NOT NULL
        CHECK (idioma IN ('es', 'pt-BR', 'sin dato')),
    hallazgos jsonb NOT NULL DEFAULT '[]'::jsonb,
    borrador text NOT NULL DEFAULT '',
    estado text NOT NULL DEFAULT 'pendiente'
        CHECK (estado IN ('pendiente', 'redactado', 'rechazado', 'aprobado')),
    hipotesis text,
    tipo_apertura text
        CHECK (
            tipo_apertura IS NULL
            OR tipo_apertura IN ('riesgo', 'oportunidad', 'esfuerzo', 'dato')
        ),
    cta text,
    industria text,
    fecha_envio date,
    fecha_reunion date,
    motivo_rechazo text,
    creado_en timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT organic_borradores_lead_id_key UNIQUE (lead_id)
);

CREATE INDEX IF NOT EXISTS idx_organic_borradores_estado
    ON organic_borradores (estado);

ALTER TABLE organic_borradores ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON organic_borradores TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
