-- LinkedIn: datos de empresa por lead y conteo de uso por cuenta.
-- Los datos de la persona van en organic_borradores.contacto (mínimos, con vencimiento).
-- Correr en el SQL Editor.

ALTER TABLE organic_borradores
    ADD COLUMN IF NOT EXISTS linkedin_empresa jsonb;

-- Una fila por consulta a LinkedIn. Sirve para frenar antes del tope mensual
-- de búsquedas de personas (LinkedIn no publica la cifra; se reportan ~300).
CREATE TABLE IF NOT EXISTS linkedin_uso (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta text NOT NULL,
    lead_id bigint,
    tipo text NOT NULL
        CHECK (tipo IN ('busqueda_personas', 'busqueda_empresas', 'empresa', 'perfil')),
    fecha date NOT NULL DEFAULT current_date,
    creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_linkedin_uso_cuenta_fecha
    ON linkedin_uso (cuenta, fecha);

ALTER TABLE linkedin_uso ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT ON linkedin_uso TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
